### ISSUE TITLE
About crop function in the App

### ISSUE THREAD

**Issue by muukii** [PingAK9/photo-editor-luts-swiftui#1]
Hello, I'd like to ask you about the cropping function in the app.
How do you create that function?
I'm thinking about how I create that on PixelEditor next version.
You know what, current PixelEditor's crop function does not have rotation.

**Comment by khanhuitse05** [comment]
Hello @muukii 
Did you mention about Adjustment Feature in later version of my app. [Luts App](https://apps.apple.com/us/app/id1525852224/)
About that I did not write by myself. I used this [package](https://cocoapods.org/pods/QCropper). It is very smooth, easy to use and familiar with iOS user.

**Comment by muukii** [comment]
@PingAK9 Hi thanks! This is what I wanted!
Because I don't have much experience how to implement the rotating function.
Now I can learn about that.
Thank you very much.
