### ISSUE TITLE
Framework not found

### ISSUE THREAD

**Issue by c0ball** [PingAK9/photo-editor-luts-swiftui#2]
After downloading the project, I started it once and closed it.
Then I installed the pods with the `pod install command` after relaunching the project I always receive the error
that the compiler is unable to find a framework: _framework not found TransitionPatch_
Any ideas on how to fix this issue?
Thanks in advance

**Comment by khanhuitse05** [comment]
Yes. This is not a package. 
It is just a Complete Project and I structure modunly
