### ISSUE TITLE
Export image as LUT code missing 

### ISSUE THREAD

**Issue by latesh** [PingAK9/photo-editor-luts-swiftui#4]
Hello! Thanks for making this app open source. One thing I couldn't find as I scanned through the source code is `Save LUTs image` functionality. Can you update the repo with the relevant code or share it in a gist? Thanks :)

**Comment by khanhuitse05** [comment]
Sorry for the late response.  @latesh
I hope you found a way by yourself.
There are no tricks here. If you want to export `Lut`. just replace your origin image with [nature lut](https://github.com/j1mmyto9/photo-editor-luts-swiftui/tree/master/colorful-room/Assets.xcassets/luts/lut-normal.imageset)

**Comment by latesh** [comment]
Thanks for your reply @j1mmyto9 

Am not sure what do you mean by just replace your origin image with nature lut! 

Just to reiterate what am saying is that: Say I open any image in this app, then I play around with the colour settings and change a bunch of values. Now in the export section, I want to export only the “lut” of the image which has the colour modifications, not export the modified image itself. See this [link](https://imgur.com/download/k7L4Dc3/) for more context.

I believe this functionality is missing from the source code in this repo but it’s there in the app on the App Store. Can you please point me towards the “Save LUTs image” source code in this repo or share example code in a gist?

Thanks!

**Comment by koptelov** [comment]
I'm also interested in the "Save LUT's image" function. 
@latesh Did you create it?

**Comment by ghost** [comment]
Only recently I saw Brightroom… And now I see your project @j1mmyto9 
I have no words for how great you did — thanks for the work you've done 👍
I would like to try all the functionality in action. Please update the repository to the latest version 🥺

**Comment by khanhuitse05** [comment]
Updated
